#pragma once

// AUTO-GENERATED by training/build_lakh_priors.py (DATA_STRATEGY.md C2).
// Do NOT edit by hand. Regenerate with:
//   python3 training/build_lakh_priors.py
// Source: Lakh MIDI lmd_matched + tagtraum CD2 MSD genre tags. See
// data/lakh_priors.json for provenance (per-genre file counts + tempo).
//
// Data-derived selection priors: per (genre, pattern-index) popularity
// weight in [0,1]. These weight the pattern POOLS at build time (pool
// ordering) and are never evaluated on the audio thread.

namespace PatternPriors
{
inline constexpr int kNumGenres = 5;
inline constexpr int kPatternCount = 28;

// [genre][patternIndex] -> popularity weight in [0,1].
inline constexpr float kWeight[kNumGenres][kPatternCount] = {
    { 0.1152f, 1.0000f, 0.5091f, 0.4667f, 1.0000f, 0.4667f, 0.1152f, 0.5091f, 0.0000f, 0.1152f, 0.4667f, 0.0000f, 0.0000f, 0.0000f, 1.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 1.0000f, 0.5091f, 0.0000f, 0.0000f, 0.0000f, 0.0000f },  // Rock
    { 0.1152f, 1.0000f, 0.5091f, 0.4667f, 1.0000f, 0.4667f, 0.1152f, 0.5091f, 0.0000f, 0.1152f, 0.4667f, 0.0000f, 0.0000f, 0.0000f, 1.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 1.0000f, 0.5091f, 0.0000f, 0.0000f, 0.0000f, 0.0000f },  // Hard Rock
    { 0.1000f, 0.8250f, 0.6000f, 1.0000f, 0.8250f, 1.0000f, 0.1000f, 0.6000f, 0.1500f, 0.1000f, 1.0000f, 0.0000f, 0.0000f, 0.0000f, 0.8250f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.1500f, 0.8250f, 0.6000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f },  // Punk
    { 0.0943f, 1.0000f, 0.5657f, 0.4444f, 1.0000f, 0.4444f, 0.0943f, 0.5657f, 0.0606f, 0.0943f, 0.4444f, 0.0000f, 0.0000f, 0.0000f, 1.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0606f, 1.0000f, 0.5657f, 0.0000f, 0.0000f, 0.0000f, 0.0000f },  // Metal
    { 0.0943f, 1.0000f, 0.5657f, 0.4444f, 1.0000f, 0.4444f, 0.0943f, 0.5657f, 0.0606f, 0.0943f, 0.4444f, 0.0000f, 0.0000f, 0.0000f, 1.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0000f, 0.0606f, 1.0000f, 0.5657f, 0.0000f, 0.0000f, 0.0000f, 0.0000f },  // Sludge
};

} // namespace PatternPriors
