#pragma once

// AUTO-GENERATED by training/build_groove_template.py (DATA_STRATEGY.md C1).
// Do NOT edit by hand. Regenerate with:
//   python3 training/build_groove_template.py
// T1.5 pins ghostVelocityLo/Hi/Threshold to 30/55/62 in the generator so a
// regenerate cannot disagree with MidiPatternLibrary's authored ghost band.
// T3.3 recentres timingMs (mean ≈ 0) and caps jitter at 3 ms rock / 2 ms metal.
// Source: Groove MIDI Dataset (GMD, CC-BY 4.0). See data/groove_templates.json
// for provenance (file/hit counts per genre). 'metal' is derived from 'rock'
// (GMD has no metal genre) by a documented tightening transform.
//
// These are data-derived per-16th velocity multipliers + microtiming offsets
// consumed as a fixed-size struct on the audio thread (no RT inference).

namespace Groove::data
{
// rock: 204 files, 115534 hits
inline constexpr float kRockVelocityMul[16] = { 1.0273f, 0.8415f, 0.9483f, 0.9223f, 1.1200f, 0.8853f, 0.9750f, 0.8935f, 1.0291f, 0.9240f, 0.9828f, 0.9562f, 1.1152f, 0.9290f, 0.9937f, 0.9098f };
inline constexpr float kRockTimingMs[16] = { -3.4760f, 10.6130f, -2.2080f, -7.1320f, -2.5860f, 5.3070f, 0.2330f, -0.3680f, -4.8340f, 10.5060f, 0.6360f, -7.6560f, -3.5970f, 5.8050f, -0.4220f, -0.8190f };
inline constexpr float kRockTimingJitterMs = 3.000f;
inline constexpr float kRockVelocityJitter = 8.000f;
inline constexpr float kRockGhostVelocityLo = 30.0f;
inline constexpr float kRockGhostVelocityHi = 55.0f;
inline constexpr unsigned char kRockGhostThreshold = 62;

// metal: 204 files, 115534 hits (derived from rock)
inline constexpr float kMetalVelocityMul[16] = { 1.0478f, 0.8415f, 0.9483f, 0.9223f, 1.1424f, 0.8853f, 0.9750f, 0.8935f, 1.0291f, 0.9240f, 0.9828f, 0.9562f, 1.1375f, 0.9290f, 0.9937f, 0.9098f };
inline constexpr float kMetalTimingMs[16] = { -1.7380f, 5.3060f, -1.1040f, -3.5660f, -1.2930f, 2.6540f, 0.1170f, -0.1840f, -2.4170f, 5.2530f, 0.3180f, -3.8280f, -1.7980f, 2.9020f, -0.2110f, -0.4090f };
inline constexpr float kMetalTimingJitterMs = 2.000f;
inline constexpr float kMetalVelocityJitter = 8.000f;
inline constexpr float kMetalGhostVelocityLo = 30.0f;
inline constexpr float kMetalGhostVelocityHi = 55.0f;
inline constexpr unsigned char kMetalGhostThreshold = 62;

// punk: 204 files, 115534 hits (derived from rock)
inline constexpr float kPunkVelocityMul[16] = { 1.0273f, 0.8415f, 0.9483f, 0.9223f, 1.1200f, 0.8853f, 0.9750f, 0.8935f, 1.0291f, 0.9240f, 0.9828f, 0.9562f, 1.1152f, 0.9290f, 0.9937f, 0.9098f };
inline constexpr float kPunkTimingMs[16] = { -0.8690f, 2.6530f, -0.5520f, -1.7830f, -0.6460f, 1.3270f, 0.0580f, -0.0920f, -1.2080f, 2.6270f, 0.1590f, -1.9140f, -0.8990f, 1.4510f, -0.1050f, -0.2050f };
inline constexpr float kPunkTimingJitterMs = 1.650f;
inline constexpr float kPunkVelocityJitter = 8.000f;
inline constexpr float kPunkGhostVelocityLo = 30.0f;
inline constexpr float kPunkGhostVelocityHi = 55.0f;
inline constexpr unsigned char kPunkGhostThreshold = 62;

} // namespace Groove::data
