#pragma once

// AUTO-GENERATED by training/build_groove_template.py (DATA_STRATEGY.md C1).
// Do NOT edit by hand. Regenerate with:
//   python3 training/build_groove_template.py
// Source: Groove MIDI Dataset (GMD, CC-BY 4.0). See data/groove_templates.json
// for provenance (file/hit counts per genre). 'metal' is derived from 'rock'
// (GMD has no metal genre) by a documented tightening transform.
//
// These are data-derived per-16th velocity multipliers + microtiming offsets
// consumed as a fixed-size struct on the audio thread (no RT inference).

namespace Groove::data
{
// rock: 204 files, 115534 hits
inline constexpr float kRockVelocityMul[16] = { 1.0273f, 0.8415f, 0.9483f, 0.9223f, 1.1200f, 0.8853f, 0.9750f, 0.8935f, 1.0291f, 0.9240f, 0.9828f, 0.9562f, 1.1152f, 0.9290f, 0.9937f, 0.9098f };
inline constexpr float kRockTimingMs[16] = { -5.4350f, 8.6540f, -4.1670f, -9.0910f, -4.5450f, 3.3480f, -1.7260f, -2.3270f, -6.7930f, 8.5470f, -1.3230f, -9.6150f, -5.5560f, 3.8460f, -2.3810f, -2.7780f };
inline constexpr float kRockTimingJitterMs = 6.000f;
inline constexpr float kRockVelocityJitter = 8.000f;
inline constexpr float kRockGhostVelocityLo = 15.0f;
inline constexpr float kRockGhostVelocityHi = 42.0f;
inline constexpr unsigned char kRockGhostThreshold = 42;

// metal: 204 files, 115534 hits (derived from rock)
inline constexpr float kMetalVelocityMul[16] = { 1.0478f, 0.8415f, 0.9483f, 0.9223f, 1.1424f, 0.8853f, 0.9750f, 0.8935f, 1.0291f, 0.9240f, 0.9828f, 0.9562f, 1.1375f, 0.9290f, 0.9937f, 0.9098f };
inline constexpr float kMetalTimingMs[16] = { -2.7170f, 4.3270f, -2.0830f, -4.5450f, -2.2720f, 1.6740f, -0.8630f, -1.1630f, -3.3970f, 4.2740f, -0.6610f, -4.8080f, -2.7780f, 1.9230f, -1.1900f, -1.3890f };
inline constexpr float kMetalTimingJitterMs = 4.200f;
inline constexpr float kMetalVelocityJitter = 8.000f;
inline constexpr float kMetalGhostVelocityLo = 15.0f;
inline constexpr float kMetalGhostVelocityHi = 42.0f;
inline constexpr unsigned char kMetalGhostThreshold = 42;

// punk: 204 files, 115534 hits (derived from rock)
inline constexpr float kPunkVelocityMul[16] = { 1.0273f, 0.8415f, 0.9483f, 0.9223f, 1.1200f, 0.8853f, 0.9750f, 0.8935f, 1.0291f, 0.9240f, 0.9828f, 0.9562f, 1.1152f, 0.9290f, 0.9937f, 0.9098f };
inline constexpr float kPunkTimingMs[16] = { -1.3590f, 2.1630f, -1.0420f, -2.2730f, -1.1360f, 0.8370f, -0.4310f, -0.5820f, -1.6980f, 2.1370f, -0.3310f, -2.4040f, -1.3890f, 0.9620f, -0.5950f, -0.6950f };
inline constexpr float kPunkTimingJitterMs = 3.300f;
inline constexpr float kPunkVelocityJitter = 8.000f;
inline constexpr float kPunkGhostVelocityLo = 15.0f;
inline constexpr float kPunkGhostVelocityHi = 42.0f;
inline constexpr unsigned char kPunkGhostThreshold = 42;

} // namespace Groove::data
