#!/usr/bin/env python3
"""Export GrooveModel centroids and ONNX model (SIMPLIFY.md Wave 1 Phase B/C).

Phase B: bottleneck extraction + centroid computation
  - Load trained GrooveClassifier checkpoint
  - Run all training data through backbone, compute per-class bottleneck centroids
  - Export as C++ header: src/inference/pattern_embeddings.h
  - Also export as JSON for reference

Phase C: ONNX export
  - Build GrooveModelForExport (backbone + embedding head + style head)
  - Copy backbone weights from classifier, randomly init embedding head
  - Export as assets/metal_groove.onnx
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

# ─── Paths ───────────────────────────────────────────────────────────────────

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DATA_DIR = _REPO_ROOT / "data" / "processed"
_MODEL_DIR = Path(__file__).resolve().parent / "models"
_INFERENCE_DIR = _REPO_ROOT / "src" / "inference"
_ASSETS_DIR = _REPO_ROOT / "assets"


def _import_groove_model():
    sys.path.insert(0, str(_MODEL_DIR.parent))
    from models.groove_model import (  # noqa: PLC0415
        GrooveClassifier,
        GrooveModelForExport,
        GrooveEmbeddingHead,
        MelCNNBackbone,
    )
    return GrooveClassifier, GrooveModelForExport, GrooveEmbeddingHead, MelCNNBackbone


def compute_centroids(
    model: nn.Module,
    X: np.ndarray,
    y: np.ndarray,
    device: torch.device,
    batch_size: int = 32,
) -> tuple[np.ndarray, np.ndarray]:
    """Compute per-class bottleneck centroids (128-dim).

    Returns:
        centroids: (n_classes, 128) mean bottleneck per class
        counts: (n_classes,) samples per class
    """
    n_classes = int(y.max()) + 1
    sums = np.zeros((n_classes, 128), dtype=np.float64)
    counts = np.zeros(n_classes, dtype=np.int64)

    model.eval()
    with torch.no_grad():
        for start in range(0, len(X), batch_size):
            end = min(start + batch_size, len(X))
            x_batch = torch.from_numpy(X[start:end]).to(device)
            y_batch = y[start:end]

            bottleneck = model.backbone(x_batch).cpu().numpy()

            for i, label in enumerate(y_batch):
                sums[label] += bottleneck[i].astype(np.float64)
                counts[label] += 1

    counts = np.maximum(counts, 1)
    centroids = (sums / counts[:, np.newaxis]).astype(np.float32)
    return centroids, counts


def export_cpp_header(centroids: np.ndarray, class_map: dict, output_path: Path):
    """Export centroids as a C++ constexpr header."""
    embedding_dim = centroids.shape[1]
    n_patterns = centroids.shape[0]

    # Create sorted list: index 0..21 → class name
    idx_to_name = {v: k for k, v in class_map.items()}

    lines = [
        "#pragma once",
        "",
        "/**",
        " * @file",
        " * @brief Precomputed pattern embeddings for MetalGrooveInference.",
        " *",
        f" * Auto-generated by training/export_centroids.py.",
        f" * {n_patterns} patterns × {embedding_dim}-dim bottleneck centroids.",
        " * Used for cosine-similarity nearest-neighbor pattern lookup at runtime.",
        " */",
        "",
        "#include <array>",
        "#include <cstddef>",
        "",
        "namespace PatternEmbeddings",
        "{",
        "",
        f"    static constexpr int kEmbeddingDim = {embedding_dim};",
        f"    static constexpr int kNumPatterns = {n_patterns};",
        "",
        "    // Precomputed CNN bottleneck centroids per pattern class.",
        "    // Generated by training/export_centroids.py",
        "    static constexpr std::array<std::array<float, kEmbeddingDim>, kNumPatterns> kCentroids = {{",
    ]

    for i in range(n_patterns):
        name = idx_to_name.get(i, f"pattern_{i}")
        vals = ", ".join(f"{v:.6f}f" for v in centroids[i])
        inner = f"{{{vals}}}"
        lines.append("        {" + inner + "},")

    lines.extend([
        "    }};",
        "",
        "}  // namespace PatternEmbeddings",
    ])

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"C++ header written: {output_path}")


def export_onnx(
    model: nn.Module,
    output_path: Path,
    device: torch.device,
    embedding_dim: int = 64,
    n_styles: int = 5,
):
    """Export GrooveModelForExport to ONNX.

    Input:  mel [1, 1, 64, 32]
    Output: groove_embedding [1, embedding_dim], style_logits [1, n_styles],
            bottleneck [1, 128]
    """
    model.eval()
    dummy_input = torch.randn(1, 1, 64, 32, device=device)

    # Trace with torch.onnx — save all data internally for BinaryData bundling
    torch.onnx.export(
        model,
        dummy_input,
        str(output_path),
        input_names=["mel"],
        output_names=["groove_embedding", "style_logits", "bottleneck"],
        dynamic_axes={
            "mel": {0: "batch"},
            "groove_embedding": {0: "batch"},
            "style_logits": {0: "batch"},
            "bottleneck": {0: "batch"},
        },
        opset_version=18,
        dynamo=False,
    )
    print(f"ONNX model exported: {output_path}")

    # Verify
    import onnx
    onnx_model = onnx.load(str(output_path))
    onnx.checker.check_model(onnx_model)
    print("  ONNX model validation: OK")

    # Print input/output shapes
    for inp in onnx_model.graph.input:
        shape = [d.dim_value for d in inp.type.tensor_type.shape.dim]
        print(f"  Input:  {inp.name} {shape}")
    for out in onnx_model.graph.output:
        shape = [d.dim_value for d in out.type.tensor_type.shape.dim]
        print(f"  Output: {out.name} {shape}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export centroids + ONNX model.")
    parser.add_argument("--checkpoint", type=Path,
                        default=_MODEL_DIR / "best_groove_model.pt")
    parser.add_argument("--data-dir", type=Path, default=_DATA_DIR)
    parser.add_argument("--model-dir", type=Path, default=_MODEL_DIR)
    parser.add_argument("--cpp-out", type=Path,
                        default=_INFERENCE_DIR / "pattern_embeddings.h")
    parser.add_argument("--onnx-out", type=Path,
                        default=_ASSETS_DIR / "metal_groove.onnx")
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--embedding-dim", type=int, default=64)
    parser.add_argument("--x-file", type=str, default="X_groove.npy")
    parser.add_argument("--y-file", type=str, default="y_groove.npy")
    parser.add_argument("--skip-onnx", action="store_true")
    args = parser.parse_args()

    device = torch.device(args.device)
    GrooveClassifier, GrooveModelForExport, GrooveEmbeddingHead, MelCNNBackbone = \
        _import_groove_model()

    # ── Load data ────────────────────────────────────────────────────────
    X = np.load(args.data_dir / args.x_file)
    y = np.load(args.data_dir / args.y_file)
    n_classes = int(y.max()) + 1
    print(f"Loaded {X.shape[0]} samples, {n_classes} classes")

    # Load class map
    class_map_path = args.data_dir / "class_map.json"
    if class_map_path.exists():
        class_map = json.loads(class_map_path.read_text())
    else:
        class_map = {f"pattern_{i:02d}": i for i in range(n_classes)}

    # ── Load checkpoint ──────────────────────────────────────────────────
    if not args.checkpoint.exists():
        print(f"ERROR: checkpoint not found: {args.checkpoint}", file=sys.stderr)
        return 1

    model = GrooveClassifier(n_classes=n_classes).to(device)
    state_dict = torch.load(args.checkpoint, weights_only=True)
    model.load_state_dict(state_dict)
    model.eval()
    print(f"Loaded checkpoint: {args.checkpoint}")

    # ── Phase B: Compute centroids ───────────────────────────────────────
    print("\n--- Phase B: Computing per-class bottleneck centroids ---")
    centroids, counts = compute_centroids(model, X, y, device)

    idx_to_name = {v: k for k, v in class_map.items()}
    for i in range(n_classes):
        name = idx_to_name.get(i, f"class_{i}")
        print(f"  {name:>30s}: {counts[i]:>5d} samples, "
              f"centroid norm={np.linalg.norm(centroids[i]):.4f}")

    # Save centroids as JSON
    centroids_json = args.model_dir / "groove_centroids.json"
    centroids_dict = {
        "embedding_dim": centroids.shape[1],
        "n_patterns": centroids.shape[0],
        "class_map": class_map,
        "centroids": centroids.tolist(),
        "sample_counts": counts.tolist(),
    }
    centroids_json.write_text(json.dumps(centroids_dict, indent=2), encoding="utf-8")
    print(f"\nCentroids saved: {centroids_json}")

    # ── Export C++ header ────────────────────────────────────────────────
    print(f"\n--- Exporting C++ header: {args.cpp_out} ---")
    args.cpp_out.parent.mkdir(parents=True, exist_ok=True)
    export_cpp_header(centroids, class_map, args.cpp_out)

    # ── Phase C: ONNX Export ─────────────────────────────────────────────
    if not args.skip_onnx:
        print(f"\n--- Phase C: Exporting ONNX model: {args.onnx_out} ---")

        # Build export model: backbone (from checkpoint) + embedding head (fresh) + style head (fresh)
        export_model = GrooveModelForExport(
            n_classes=n_classes,
            embedding_dim=args.embedding_dim,
            n_styles=5,
        ).to(device)

        # Copy backbone weights
        export_model.backbone.load_state_dict(model.backbone.state_dict())

        # Embedding head and style head are randomly initialized
        # (They'll be trained separately with triplet loss if needed)
        print("  Note: embedding head weights are randomly initialized.")
        print("  For production, train with triplet loss on the embedding head.")
        print("  For now, centroids in bottleneck space will be used instead.")

        args.onnx_out.parent.mkdir(parents=True, exist_ok=True)
        try:
            export_onnx(export_model, args.onnx_out, device,
                        embedding_dim=args.embedding_dim, n_styles=5)
        except Exception as e:
            print(f"WARNING: ONNX export failed: {e}", file=sys.stderr)
            print("Centroids were exported successfully. ONNX can be generated later.")
            return 0

    print("\n✓ Centroid export complete.")
    print(f"  C++ header: {args.cpp_out}")
    print(f"  ONNX model: {args.onnx_out}")
    print(f"  Centroids JSON: {centroids_json}")
    print()
    print("Next: Build plugin with MetalGrooveInference integration (Wave 3).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
